### PR TITLE
Fix das calls, dafgda, dafus. 

### PR DESCRIPTION
**Pull request by fyellin**
Remove some Python2 stuff.  Fix broken cspyce calls.

### CODE REVIEW

**Comment by fyellin** [comment]
I thought this was done.  I wasn't expecting tests to fail.  Can I convert it back to a draft?

**Comment by fyellin** [comment]
It appears that I pass on 3.9, 3.10, and 3.11, but something is failing on 3.8.  Will investigate further.

**Comment by fyellin** [comment]
Hold again.  Found a small problem.  Be done by noon.

**Comment by fyellin** [comment]
All tests were successful.   Everything working except for coverage.  I can write some basic tests for the dasxxx if you want.  I don't know enough about the other two functions.

**Comment by rfrenchseti** [comment]
Try creating a new branch that is a merge of your changes here and the branch "17-create_cspyce_unit_tests". Then look under "unittests" for the test file "test_d.py". Some of the das tests will be marked "fail_". Just change those back to "test_". Then run with pytest and see what happens.

These tests were derived from spiceypy, which may take different inputs and give different results, so if you can find a way to make the test work in a way that makes you happy, let us know what to change.

**Comment by fyellin** [comment]
I created some unit tests, then accidentally did a push before doing the
commit.  The empty unit test is failing.  I just redid it.  Hopefully this
will work.

Everything was passing before I wrote my own unittests, and at least on my
own machine, the unittests pass.

This time for sure.

**Review by rfrenchseti — DISMISSED** [review]
- I found the following docstring errors:
  - `dasrdi`: End of range of DAS *character* integer addresses.
  - `dasrdd`: End of range of DAS *character* floating-point addresses.
  - `dasadc`: Says takes a byte_array, but it actually takes a list of strings.
  - `dasrdc`: Says the return value is a `byte_array` having "updated values". This seems wrong since it actually returns a list of strings.

**Comment by fyellin** [comment]
Updated documentation.

**Comment by rfrenchseti** [comment]
I have not gone through all of the doc strings. At some point we should do that as a separate task for all of cspyce.

**Review by rfrenchseti — APPROVED** [review]

**Pull request merged**
