### PR TITLE
Don't re-read file to get hash code

### PR DESCRIPTION
**Pull request by fyellin**
Just calculate the hash while you have the file contents.  Don't read twice.
Also change .format() to f string, which uncovered a bug.

Note.  I'm slightly unhappy about creating byte arrays of size 9meg.  It's possible to buffer the read/write/hash into chunks.  But that's a bigger change.

### CODE REVIEW

**Comment by rfrenchseti** [comment]
You didn't ask for a review - is this pull ready to go?

**Comment by fyellin** [comment]
I put down both you and Emily as reviewers, didn't I?  Yes, it is ready.

**Comment by fyellin** [comment]
I mentioned that I'm a little bit bothered by the fact that at least one of the files is 9meg, and this code reads the file into a single array, and then writes it out.  For things that big, buffered is better.  I can change the code to read the file in 64K chunks, which is more memory friendly.

**Comment by fyellin** [comment]
Is there anyway to tell codecov that we don't care about coverage of stuff that's part of the testing framework?

**Comment by rfrenchseti** [comment]
No, there are no reviewers requested.

Depending on which part of the testing framework you're talking about, I actually like having it included in the code coverage. For the actual tests, it's how we find copy-paste errors where multiple tests have the same function name.

**Comment by fyellin** [comment]
Oh.  Used a different mechanism to create the pull request.  Previously, I
didn't have to hit the "request review" button.

**Comment by rfrenchseti** [comment]
So you said "I can change the code to read the file in 64K chunks, which is more memory friendly." Shouldn't we wait for this change to review and merge this pull?

**Comment by fyellin** [comment]
Mark talked me out of it. These are just tests, and it's working now.

**Comment by rfrenchseti** [comment]
Due to conflicts between this and what Emilie is currently working on, she will be merging this branch into her work and then submitting a single unified pull request. Please do not make any further modifications to this branch.

**Comment by fyellin** [comment]
Closing the pull request.  I will leave the branch here until Emilie says it's okay to delete it.

**Comment by fyellin** [comment]
I was avoiding closing this until Emilie had merged in whatever she
needed.  May I delete the branch?

**Comment by rfrenchseti** [comment]
Your previous comment said "Closing the pull request. I will leave the branch here until Emilie says it's okay to delete it." but it wasn't closed, so I closed it. Let's wait to delete the branch until Emilie's new pull is working properly.

**Comment by esimpsons3ti** [comment]
I have pushed new commits to my branch. Let's see if the tests pass.

**Pull request closed without merging**
