### PR TITLE
Convert test_kernels.py to pytest

### PR DESCRIPTION
**Pull request by fyellin**
Separate big test in test_kernels.py to several smaller tests
Use automatic converter to convert to pytest.  
Add some fixtures to simplify the code.

### CODE REVIEW

**Comment by fyellin** [comment]
Note that this pull request is really two pull requests combined into one.

#1) I wanted to break up test_kernels into smaller tests.  Since tests can be run individually, this vastly simplifies dealing with errors.  There is very little change between the original file and this file: just the addition of some `def test_xxx()` lines.

#2) I found a tool that converts Unittests into pytest.  I took the results of (1), ran this tool on it, and then made some small changes to it.  This pretty much changes every line from its unittest form to its pytest form.

If you think I should just do #1 and skip #2, or do it as a separate push, let me know.

**Comment by rfrenchseti** [comment]
I think this is fine to do together, and a very useful change in general. The only reason I haven't approved it is you didn't send it out for review yet.

**Comment by fyellin** [comment]
Not sure.  I thought I sent it as a pull request rather than a preview.  In any case, it seems to be a pull request now.

**Comment by rfrenchseti** [comment]
It's a pull request, you just didn't ask for a review from anyone so I was waiting to see if you had more work to do.

**Comment by fyellin** [comment]
Ah, I forgot about that part.

**Pull request closed without merging**
